// All events

export const eventsData = [
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "2:00 PM",
    date: "July 23rd",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "1:30 PM",
    date: "July 30th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "2:30 PM",
    date: "Aug 13th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "2:30 PM",
    date: "Aug 18th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "2:30 PM",
    date: "Aug 27th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "10:00 AM",
    date: "Sept 18th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "1:50 PM",
    date: "Sept 25th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "1:45 PM",
    date: "Oct 6th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "9:30 AM",
    date: "Oct 23rd",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "9:30 AM",
    date: "Nov 20th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "10:00 AM",
    date: "Dec 3rd",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "1:50 PM",
    date: "Dec 11th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "9:30 AM",
    date: "Dec 18th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
  {
    eventName: "Broncos Game",
    location: "1801 Mile High Stadium Cir Denver CO 80204",
    time: "TBD",
    date: "Jan 7th",
    description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    extraInformation: "Dolor in reprehenderit in voluptate...",
  },
 
];

// apple bees, tournaments, field clean ups, overland youth, workouts, tryouts,


